### ISSUE TITLE
Preload code missing

### ISSUE THREAD

**Issue by ELubicz** [analogdevicesinc/EV-SC594-EZKIT-Audio-Starter#1]
Hello,

Would it be possible to include the code and the project file that yields the ezkitSC594W_preload_core0 file? When I build the sc594w_preload_Core0 project available under the `CrossCore Embedded Studio 2.10.0\SHARC\ldr\init_code\SC59x_Init\sc594w_preload_Core0\` folder, I get a different binary (see [sc594w_preload_Core0.zip](https://github.com/analogdevicesinc/EV-SC594-EZKIT-Audio-Starter/files/14208662/sc594w_preload_Core0.zip)).

Thanks in advance!

**Comment by rbutler87** [comment]
Hi @ELubicz , 

I apologize for not responding to this previously. Typically we don't re-release the software used to create the pre-init and initcode but we do archive the binaries to reduce the variance in startup code across CCES releases.

This particular set came from CCES version 2.10.1 and you should be able to recreate the same binary using the init code source released in that version which you can download here: https://download.analog.com/tools/CrossCoreEmbeddedStudio/Releases/Release_2.10.1/ADI_CrossCoreEmbeddedStudio-Rel2.10.1.exe
